devtools::load_all()
# piggyback::pb_download()
upthat::runUpthat()
# library(upthat)
# shinyApp(ui = shinyAppUI, server = shinyAppServer)
# upthat::runUpthat()
# library(shiny)
# library(leaflet)
# library(upthat)
#
source("https://github.com/atfutures-labs/upthat/raw/master/R/ui.R")
source("https://github.com/atfutures-labs/upthat/raw/master/R/server.R")

library(shiny)
shiny::shinyApp(ui = shinyAppUI, server = shinyAppServer)
